RETIREMENT_INDICATOR = "RETIREMENT_INDICATOR"
INSURANCE_INDICATOR = "INSURANCE_INDICATOR"
INVESTMENT_INDICATOR = "INVESTMENT_INDICATOR"
EMPLOYMENT_BENEFIT_INDICATOR = "EMPLOYMENT_BENEFIT_INDICATOR"
BANKING_INDICATOR = "BANKING_INDICATOR"
PROPERTY_INDICATOR = "PROPERTY_INDICATOR"
BENEFICIARY_INDICATOR = "BENEFICIARY_INDICATOR"
GOVERNMENT_BENEFIT_INDICATOR = "GOVERNMENT_BENEFIT_INDICATOR"
OTHER_FINANCIAL_INDICATOR = "OTHER_FINANCIAL_INDICATOR"

DISCOVERY_CATEGORY_VALUES = {
    RETIREMENT_INDICATOR,
    INSURANCE_INDICATOR,
    INVESTMENT_INDICATOR,
    EMPLOYMENT_BENEFIT_INDICATOR,
    BANKING_INDICATOR,
    PROPERTY_INDICATOR,
    BENEFICIARY_INDICATOR,
    GOVERNMENT_BENEFIT_INDICATOR,
    OTHER_FINANCIAL_INDICATOR,
}