"""add discovery intelligence foundation

Revision ID: fb94d1fd5ad1
Revises: d2f4b8c9a701
Create Date: 2026-07-22 03:16:59.197092

"""
from alembic import op
import sqlalchemy as sa



revision = 'fb94d1fd5ad1'
down_revision = 'd2f4b8c9a701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_scans_id'), 'discovery_scans', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_scans_status'), 'discovery_scans', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_scans_user_id'), 'discovery_scans', ['user_id'], unique=False)
    op.create_table('evidence_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('matched_terms_encrypted', sa.Text(), nullable=True),
    sa.Column('evidence_excerpt_encrypted', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['discovery_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_findings_category'), 'evidence_findings', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_findings_document_id'), 'evidence_findings', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_findings_id'), 'evidence_findings', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_findings_review_status'), 'evidence_findings', ['review_status'], unique=False)
    op.create_index(op.f('ix_evidence_findings_scan_id'), 'evidence_findings', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_findings_scan_id'), table_name='evidence_findings')
    op.drop_index(op.f('ix_evidence_findings_review_status'), table_name='evidence_findings')
    op.drop_index(op.f('ix_evidence_findings_id'), table_name='evidence_findings')
    op.drop_index(op.f('ix_evidence_findings_document_id'), table_name='evidence_findings')
    op.drop_index(op.f('ix_evidence_findings_category'), table_name='evidence_findings')
    op.drop_table('evidence_findings')
    op.drop_index(op.f('ix_discovery_scans_user_id'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_status'), table_name='discovery_scans')
    op.drop_index(op.f('ix_discovery_scans_id'), table_name='discovery_scans')
    op.drop_table('discovery_scans')
    # ### end Alembic commands ###
